apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mgr-postgres
  namespace: service-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-mgr-postgres
  template:
    metadata:
      labels:
        app: service-mgr-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: service-mgr-db-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: service-mgr-postgres-pvc

