apiVersion: v1
kind: Service
metadata:
  name: service-mgr-postgres
  namespace: service-mgr
spec:
  type: ClusterIP
  selector:
    app: service-mgr-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

