apiVersion: v1
kind: Secret
metadata:
  name: service-mgr-db-secret
  namespace: service-mgr
type: Opaque
stringData:
  POSTGRES_USER: svcmanager
  POSTGRES_PASSWORD: supersecurepassword
  POSTGRES_DB: service_mgmt

