apiVersion: v1
kind: ServiceAccount
metadata:
  name: startup-checker
  namespace: access-pending
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: startup-checker-role
  namespace: access-pending
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: startup-checker-binding
  namespace: access-pending
subjects:
- kind: ServiceAccount
  name: startup-checker
  namespace: access-pending
roleRef:
  kind: Role
  name: startup-checker-role
  apiGroup: rbac.authorization.k8s.io