apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-mgr.fullname" . }}-secrets
  labels:
    {{- include "service-mgr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}