apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-mgr.fullname" . }}-frontend
  labels:
    {{- include "service-mgr.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "service-mgr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend